### ISSUE TITLE
Copyright Takedown "HifoColo's Masterio 12'' Amp-ed MapMuss"

### ISSUE THREAD

**Issue by harshadeepan** [ShOeLaYz/MusicCloud#1]
Dear @ShOeLaYz 
Please Takedown This Whole Project Or Else You'll Need To ATTEND The Court
**Hifocolo's Masterio IS NOT AVAILABLE FOR COMMERCIAL PURPOSES**

Regards
IamHD

**Comment by ShOeLaYz** [comment]
Ok Ok Chill
